ALTER TABLE "Trip"
  ADD COLUMN "quoteId" TEXT,
  ADD COLUMN "fareBalancePaid" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN "cashBalancePaid" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN "externalPaid" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN "externalPaymentMethod" TEXT;

CREATE UNIQUE INDEX "Trip_quoteId_key" ON "Trip"("quoteId");

ALTER TABLE "Trip"
  ADD CONSTRAINT "Trip_quoteId_fkey"
  FOREIGN KEY ("quoteId") REFERENCES "FareQuote"("id") ON DELETE SET NULL ON UPDATE CASCADE;
