services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: taxi
      POSTGRES_PASSWORD: taxi
      POSTGRES_DB: master_travel_project
    ports:
      - "5433:5432"
    volumes:
      - taxi-postgres:/var/lib/postgresql/data

volumes:
  taxi-postgres:
