services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: master_travel_project
      POSTGRES_PASSWORD: master_travel_project
      POSTGRES_DB: master_travel_project
    ports:
      - "5433:5432"
    volumes:
      - master-travel-project-postgres:/var/lib/postgresql/data

volumes:
  master-travel-project-postgres:
