import { inject } from 'vue'
import { PaymentConfigCard, PaymentCnConfigModes, PaymentCurrencyTabs, PaymentScopeTabs } from './payments.components.js'
import { PaymentConfigEditor } from './payment-config-editor.component.js'

export const PaymentsPage = {
  name: 'PaymentsPage',
  components: { PaymentConfigCard, PaymentConfigEditor, PaymentCnConfigModes, PaymentCurrencyTabs, PaymentScopeTabs },
  setup() { return inject('adminPaymentsContext') },
  template: String.raw`<section v-if="view==='payments'" class="payment-settings-admin">
  <header class="payment-hero"><div class="payment-hero-content"><span class="payment-kicker">PAYMENT CONFIGURATION</span><h1>支付設定</h1><p>查看可配置的支付方式，選擇環境後完成技術接入；正式採用由財務管理中心控制。</p></div><div class="payment-hero-actions"><span class="payment-hero-state"><i></i>技術配置模式</span></div></header>
  <div class="payment-notice"><div class="payment-notice-icon">✓</div><div><strong>技術配置中心</strong><span>此頁只保存支付渠道技術資料與連線測試結果。正式啟用、收款、退款、出款、結算及對帳由財務管理中心控制。</span></div></div>
  <PaymentScopeTabs :scope="paymentConfigFilter.scope" @update:scope="paymentConfigFilter.scope = $event" />
  <PaymentCurrencyTabs :currency="paymentConfigFilter.currency" :counts="{ HKD: currencyConfigCount('HKD'), RMB: currencyConfigCount('RMB'), all: currencyConfigCount('all') }" @update:currency="paymentConfigFilter.currency = $event" />
  <section v-if="paymentConfigFilter.currency === 'all' || paymentConfigFilter.currency === 'HKD'" class="payment-settlement-section" aria-labelledby="payment-hkd-title"><div class="payment-section-heading"><div><span class="payment-label">結算貨幣</span><h2 id="payment-hkd-title">港幣結算</h2></div></div><div class="payment-provider-directory-grid"><article class="payment-provider-directory-card"><header><div class="payment-provider-identity"><div class="payment-provider-directory-logo"><img src="/payment-providers/alipayhk-logo.png" alt="AlipayHK" /></div></div><span class="payment-status enabled">可配置</span></header><p>AlipayHK 支援 HKD／RMB 收款，結算貨幣為 HKD。</p><p>WAP · HKD／RMB 收款 · HKD 結算</p><div class="payment-provider-environments"><button type="button" @click="openPaymentEditor(paymentConfigs.find(config => config.provider === 'AlipayHK' && config.environment === 'sandbox' && config.settlementCurrency === 'HKD' && (paymentConfigFilter.scope === 'all' || config.scope === paymentConfigFilter.scope)), 'sandbox')">{{paymentConfigs.some(config => config.provider === 'AlipayHK' && config.environment === 'sandbox' && config.settlementCurrency === 'HKD' && (paymentConfigFilter.scope === 'all' || config.scope === paymentConfigFilter.scope)) ? '查看／編輯 Sandbox' : '配置 Sandbox'}}</button><button type="button" @click="openPaymentEditor(paymentConfigs.find(config => config.provider === 'AlipayHK' && config.environment === 'production' && config.settlementCurrency === 'HKD' && (paymentConfigFilter.scope === 'all' || config.scope === paymentConfigFilter.scope)), 'production')">{{paymentConfigs.some(config => config.provider === 'AlipayHK' && config.environment === 'production' && config.settlementCurrency === 'HKD' && (config.scope === paymentConfigFilter.scope || paymentConfigFilter.scope === 'all')) ? '查看／編輯 Production' : '配置 Production'}}</button></div></article></div><section v-if="visiblePaymentConfigs().some(item => (item.settlementCurrency || item.currency) === 'HKD')" class="payment-settlement-configs"><div class="payment-section-heading"><div><span class="payment-label">已保存配置</span><h3>港幣結算配置</h3></div><span>{{visiblePaymentConfigs().filter(item => (item.settlementCurrency || item.currency) === 'HKD').length}} 項</span></div><div class="payment-grid"><PaymentConfigCard v-for="config in visiblePaymentConfigs().filter(item => (item.settlementCurrency || item.currency) === 'HKD')" :key="config.id" :config="config" :can-write="canWrite" @edit="openPaymentEditor" @duplicate="duplicatePaymentConfig" /></div></section></section>
      <section v-if="paymentConfigFilter.currency === 'all' || paymentConfigFilter.currency === 'RMB'" class="payment-settlement-section" aria-labelledby="payment-rmb-title"><div class="payment-section-heading"><div><span class="payment-label">結算貨幣</span><h2 id="payment-rmb-title">人民幣結算</h2></div></div><div class="payment-provider-directory-grid"><article class="payment-provider-directory-card payment-provider-directory-card-cn"><header><div class="payment-provider-identity"><div class="payment-provider-directory-logo"><img src="/payment-providers/alipay-cn-logo.svg" alt="支付寶" /></div><div><strong>內地支付寶</strong><small>中國內地 · RMB 結算</small></div></div><span class="payment-status draft">尚未接入</span></header><p>內地支付寶是一個獨立支付配置，包含四種接入模式。</p><div class="payment-provider-mode-list"><div v-for="mode in [{key:'h5',label:'手機網站支付／H5',interface:'H5'},{key:'app',label:'App 支付',interface:'APP'},{key:'page',label:'電腦網站支付',interface:'PAGE'},{key:'isv',label:'服務商模式',interface:'服務商'}]" :key="mode.key" class="payment-provider-mode"><div><strong>{{mode.label}}</strong><small>{{mode.interface}} · RMB 結算</small></div><button type="button" disabled>尚未接入</button></div></div><div class="payment-provider-not-connected">目前只完成 UI 佈局，尚未接入保存、編輯或第三方連線測試。</div><PaymentCnConfigModes /></article></div></section>
      <section v-if="paymentConfigFilter.scope === 'driver-settlement'" class="payment-boundary-note"><strong>出款服務技術配置</strong><span>此處只配置出款服務與技術連線；司機應付金額、結算結果、出款操作及對帳由財務管理中心負責。</span></section>
  <div v-if="paymentSettingsSaved" class="payment-saved">✓ 技術配置已保存</div>
  <PaymentConfigEditor v-if="paymentEditorOpen" :config="selectedPaymentConfig" :step="paymentEditorStep" :can-write="canWrite" :test-result="paymentTestResult" @close="closePaymentEditor" @update:step="paymentEditorStep = $event" @test="testPaymentConfig" @save="savePaymentConfigDraft" />
</section>`
}
