import { inject, onMounted, reactive, ref } from 'vue'
import './PhoneLoginDevelopmentSettings.css'

export const PhoneLoginDevelopmentSettings = {
  name: 'PhoneLoginDevelopmentSettings',
  props: { canWrite: { type: Boolean, default: false } },
  setup(props) {
    const { api } = inject('adminLoginSettingsContext')
    const settings = reactive({ passengerEnabled: false, driverEnabled: false, verificationCode: '' })
    const dirty = ref(false); const loading = ref(false); const saving = ref(false); const error = ref(''); const saved = ref(false)
    const load = async () => { loading.value = true; try { const result = await api('/settings/phone-login-development'); settings.passengerEnabled = Boolean(result.passengerEnabled); settings.driverEnabled = Boolean(result.driverEnabled); dirty.value = false } catch (cause) { error.value = cause?.message || '開發模式設定載入失敗' } finally { loading.value = false } }
    const updateSetting = (field, value) => { if (!props.canWrite) return; settings[field] = value; dirty.value = true; saved.value = false }
    const markDirty = () => { if (props.canWrite) { dirty.value = true; saved.value = false } }
    const save = async () => { if (!props.canWrite || saving.value || (settings.verificationCode && !/^\d{5}$/.test(settings.verificationCode))) return; saving.value = true; error.value = ''; try { const result = await api('/settings/phone-login-development', { method: 'POST', body: JSON.stringify({ passengerEnabled: settings.passengerEnabled, driverEnabled: settings.driverEnabled, ...(settings.verificationCode ? { verificationCode: settings.verificationCode } : {}) }) }); settings.passengerEnabled = Boolean(result.passengerEnabled); settings.driverEnabled = Boolean(result.driverEnabled); settings.verificationCode = ''; dirty.value = false; saved.value = true } catch (cause) { error.value = cause?.message || '開發模式設定保存失敗' } finally { saving.value = false } }
    onMounted(load)
    return { settings, dirty, loading, saving, error, saved, updateSetting, markDirty, save }
  },
  template: String.raw`<section class="phone-login-development-settings login-settings-card" aria-labelledby="phone-login-development-title"><div class="login-settings-card-header"><div><span class="section-kicker">DEVELOPMENT ACCESS</span><h3 id="phone-login-development-title">開發模式登入</h3><p>獨立控制手機號碼登入的開發驗證模式，不會修改其他登入方式設定。</p></div><span class="login-method-count">手機號碼</span></div><p v-if="loading" class="phone-login-development-feedback">載入中…</p><p v-if="error" class="phone-login-development-feedback error">{{ error }}</p><div class="phone-login-development-grid"><label class="phone-login-development-toggle"><span><strong>乘客端</strong><small>允許乘客端使用指定驗證碼登入／註冊</small><em :class="settings.passengerEnabled ? 'is-enabled' : 'is-disabled'">{{ settings.passengerEnabled ? '目前：開啟' : '目前：關閉' }}</em></span><input type="checkbox" :checked="settings.passengerEnabled" :disabled="!canWrite || loading" @change="updateSetting('passengerEnabled', $event.target.checked)"></label><label class="phone-login-development-toggle"><span><strong>司機端</strong><small>允許司機端使用指定驗證碼登入／註冊</small><em :class="settings.driverEnabled ? 'is-enabled' : 'is-disabled'">{{ settings.driverEnabled ? '目前：開啟' : '目前：關閉' }}</em></span><input type="checkbox" :checked="settings.driverEnabled" :disabled="!canWrite || loading" @change="updateSetting('driverEnabled', $event.target.checked)"></label><label class="phone-login-development-code"><span>指定驗證碼</span><input v-model="settings.verificationCode" type="password" inputmode="numeric" maxlength="5" autocomplete="off" placeholder="輸入 5 位驗證碼" :disabled="!canWrite || loading || saving" @input="markDirty"></label></div>  <div class="phone-login-development-actions"><p v-if="saved" class="phone-login-development-feedback success">開發模式設定已保存</p><button type="button" class="login-method-save" :disabled="!canWrite || !dirty || saving || Boolean(settings.verificationCode && !/^\d{5}$/.test(settings.verificationCode))" @click="save">{{ saving ? '保存中…' : '保存開發模式設定' }}</button></div></section>`
}
