export function createAdministratorsActions({ api, administratorForm, load, error, displayError, requestConfirmation, notify }) {
  function resetAdministrator() { administratorForm.value = { id: '', username: '', displayName: '', role: 'OPERATOR', enabled: true, password: '' } }
  function editAdministrator(item) { administratorForm.value = { ...item, password: '' } }
  async function saveAdministrator() { try { await api('/admin/administrators', { method: 'POST', body: JSON.stringify(administratorForm.value) }); administratorForm.value = null; await load() } catch (err) { error.value = displayError(err) } }
  async function disableAdministrator(item) { if (!await requestConfirmation({ title: '停用管理員', message: `確定停用 ${item.displayName}？`, confirmLabel: '停用', danger: true })) return; try { await api(`/admin/administrators/${item.id}`, { method: 'DELETE' }); notify('管理員已停用'); await load() } catch (err) { error.value = displayError(err); notify(error.value, 'error') } }
  async function unlockAdministrator(item) { if (!await requestConfirmation({ title: '解除帳戶鎖定', message: `確定解除 ${item.displayName} 的登入鎖定？`, confirmLabel: '解除鎖定' })) return; try { await api(`/admin/administrators/${item.id}/unlock`, { method: 'POST' }); notify('帳戶鎖定已解除'); await load() } catch (err) { error.value = displayError(err); notify(error.value, 'error') } }
  async function revokeAdministratorSessions(item) { if (!await requestConfirmation({ title: '撤銷登入工作階段', message: `確定登出 ${item.displayName} 的所有裝置？`, confirmLabel: '全部登出', danger: true })) return; try { const result = await api(`/admin/administrators/${item.id}/revoke-sessions`, { method: 'POST' }); notify(`已撤銷 ${result.revokedCount} 個工作階段`); await load() } catch (err) { error.value = displayError(err); notify(error.value, 'error') } }
  return { resetAdministrator, editAdministrator, saveAdministrator, disableAdministrator, unlockAdministrator, revokeAdministratorSessions }
}
