name: driver_web
description: EC Travel driver web UI
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/order-history-origin.svg
    - assets/order-history-destination.svg
    - assets/completed-origin.svg
    - assets/completed-destination.svg
    - assets/completed-divider.svg
    - assets/in-progress-origin.svg
    - assets/in-progress-route-line.svg
    - assets/in-progress-destination.svg
    - assets/in-progress-star.svg
    - assets/in-progress-phone.svg
    - assets/in-progress-arrow-right.svg
    - assets/in-progress-chevron-left.svg
    - assets/in-progress-route.svg
    - assets/in-progress-divider.svg
    - assets/car.svg
    - assets/master-app-logo.png
    - assets/login-wechat.svg
    - assets/login-apple.svg
    - assets/circle-x.svg
    - assets/apple.svg
    - assets/chevron-down.svg
    - assets/camera.svg
    - assets/route-origin.svg
    - assets/route-destination.svg
    - assets/route-driver.svg
    - assets/icon-home.svg
    - assets/icon-person.svg
    - assets/home-bell.svg
    - assets/home-status-dot.svg
    - assets/home-toggle.svg
    - assets/home-divider.svg
    - assets/home-star.svg
    - assets/home-origin-dot.svg
    - assets/home-destination-dot.svg
    - assets/home-order-divider.svg
    - assets/home-user.svg
    - assets/home-nav-home.svg
    - assets/home-nav-person.svg
    - assets/profile-bell.svg
    - assets/profile-user.svg
    - assets/profile-chevron.svg
    - assets/profile-divider.svg
    - assets/profile-vehicle.svg
    - assets/profile-clipboard.svg
    - assets/profile-wechat.svg
    - assets/profile-fps.svg
    - assets/profile-toggle.svg
    - assets/profile-headphones.svg
    - assets/order-detail-origin.svg
    - assets/order-detail-destination.svg
    - assets/order-detail-car.svg
    - assets/order-detail-check.svg
    - assets/order-detail-car-mpv.svg
    - assets/vehicle-car-front.svg
