abstract final class DriverRouteNames {
  static const login = '/';
  static const registration = '/registration';
  static const reviewStatus = '/review-status';
  static const home = '/home';
  static const orders = '/orders';
  static const orderDetail = '/orders/detail';
  static const completedOrderDetail = '/orders/history/detail';
  static const orderHistory = '/orders/history';
  static const profile = '/profile';
  static const profileEdit = '/profile/edit';
  static const about = '/profile/about';
  static const contactSupport = '/profile/contact-support';
  static const vehicle = '/profile/vehicle';
  static const flightQuery = '/profile/flight-query';
  static const currency = '/profile/currency';
  static const settlementOverview = '/profile/settlement';
  static const wechatPayment = '/profile/wechat-payment';
  static const addVehicle = '/profile/vehicle/add';
  static const vehicleLegacy = '/profile/vehicle-legacy';
  static const languageSettings = '/profile/language';
  static const notificationSettings = '/profile/notifications';
  static const orderAccepted = '/orders/accepted';
  static const orderInProgress = '/orders/in-progress';
  static const orderCompleted = '/orders/completed';
}
