export function createVehiclesActions({ api, view, categories, vehicles, extras, distancePricing, routeMinimumFareForm, categoryForm, vehicleForm, extraForm, pricingCurrency, severeWeatherEnabled, extraSortId, load, error, displayError, requestConfirmation, notify, t }) {
  function editExtra(item) { extraForm.value = { triggerType: item.triggerType || (item.requiredForImmediate ? 'IMMEDIATE' : 'NONE'), triggerEnabled: item.triggerEnabled !== false, nightStartTime: item.nightStartTime || '22:00', nightEndTime: item.nightEndTime || '06:00', ...item } }
  function resetExtra() { extraForm.value = { id: '', label: '', price: 0, currency: pricingCurrency.value === 'HKD' ? 'HKD$' : 'RMB¥', enabled: true, order: extras.value.length + 1, requiredForImmediate: false, requiredWithinMinutes: null, triggerType: 'NONE', triggerEnabled: true, nightStartTime: '22:00', nightEndTime: '06:00' } }
  async function saveExtra() { const currentView = view.value; try { const form = extraForm.value; await api('/admin/vehicle-extras', { method: 'POST', body: JSON.stringify({ ...form, requiredForImmediate: form.triggerType === 'IMMEDIATE' }) }); if (form.triggerType === 'WEATHER') await api('/settings', { method: 'POST', body: JSON.stringify({ severeWeatherEnabled: severeWeatherEnabled.value }) }); extraForm.value = null; view.value = currentView; await load(); view.value = currentView } catch (err) { view.value = currentView; error.value = displayError(err) } }
  async function moveExtra(direction) { const index = extras.value.findIndex(extra => extra.id === extraSortId.value); const target = index + direction; if (index < 0 || target < 0 || target >= extras.value.length) return; const reordered = [...extras.value]; const [item] = reordered.splice(index, 1); reordered.splice(target, 0, item); try { await Promise.all(reordered.map((extra, order) => api('/admin/vehicle-extras', { method: 'POST', body: JSON.stringify({ ...extra, order: order + 1 }) }))); await load() } catch (err) { error.value = displayError(err) } }
  async function showOnlyExtra(item) { const currentView = view.value; try { await Promise.all(extras.value.filter(extra => extra.id !== item.id && extra.enabled !== false).map(extra => api('/admin/vehicle-extras', { method: 'POST', body: JSON.stringify({ ...extra, enabled: false }) }))); await api('/admin/vehicle-extras', { method: 'POST', body: JSON.stringify({ ...item, enabled: true }) }); await load(); view.value = currentView } catch (err) { error.value = displayError(err) } }
  async function toggleSevereWeather() { try { const updated = await api('/settings', { method: 'POST', body: JSON.stringify({ severeWeatherEnabled: !severeWeatherEnabled.value }) }); severeWeatherEnabled.value = Boolean(updated.severeWeatherEnabled) } catch (err) { error.value = displayError(err) } }
  async function removeExtra(item) { if (!await requestConfirmation({ title: '刪除額外服務', message: `${t('remove')} ${item.label}?`, confirmLabel: '刪除', danger: true })) return; try { await api(`/admin/vehicle-extras/${item.id}`, { method: 'DELETE' }); notify('額外服務已刪除'); await load() } catch (err) { error.value = displayError(err); notify(error.value, 'error') } }
  function editVehicle(item) { vehicleForm.value = { ...item } }
  function editCategory(item) { categoryForm.value = { ...item } }
  function resetCategory() { categoryForm.value = { id: '', name: '', tabLabel: '', order: categories.value.length + 1, enabled: true } }
  function resetVehicle() { vehicleForm.value = { id: crypto.randomUUID(), categoryId: categories.value[0]?.id || '', brand: '', model: '', series: '', seats: 4, image: '', colorLabel: '不限顏色', modelChoiceLabel: '', enabled: true, order: 1 } }
  async function saveCategory() { try { await api('/admin/vehicle-categories', { method: 'POST', body: JSON.stringify(categoryForm.value) }); categoryForm.value = null; await load() } catch (err) { error.value = displayError(err) } }
  async function toggleCategory(item) { try { await api('/admin/vehicle-categories', { method: 'POST', body: JSON.stringify({ ...item, enabled: !item.enabled }) }); await load() } catch (err) { error.value = displayError(err) } }
  async function saveVehicle() { try { await api('/admin/vehicles', { method: 'POST', body: JSON.stringify(vehicleForm.value) }); vehicleForm.value = null; await load() } catch (err) { error.value = displayError(err) } }
  async function toggleVehicle(item) { try { await api('/admin/vehicles', { method: 'POST', body: JSON.stringify({ ...item, enabled: !item.enabled }) }); await load() } catch (err) { error.value = displayError(err) } }
  async function removeCategory(item) { if (!await requestConfirmation({ title: '刪除車型分類', message: `${t('remove')} ${item.name}?`, confirmLabel: '刪除', danger: true })) return; try { await api(`/admin/vehicle-categories/${item.id}`, { method: 'DELETE' }); notify('車型分類已刪除'); await load() } catch (err) { error.value = displayError(err); notify(error.value, 'error') } }
  async function removeVehicle(item) { if (!await requestConfirmation({ title: '刪除車型', message: `${t('remove')} ${item.model}?`, confirmLabel: '刪除', danger: true })) return; try { await api(`/admin/vehicles/${item.id}`, { method: 'DELETE' }); notify('車型已刪除'); await load() } catch (err) { error.value = displayError(err); notify(error.value, 'error') } }
  return { editExtra, resetExtra, saveExtra, moveExtra, showOnlyExtra, toggleSevereWeather, removeExtra, editVehicle, editCategory, resetCategory, resetVehicle, saveCategory, toggleCategory, saveVehicle, toggleVehicle, removeCategory, removeVehicle }
}
