import { inject } from 'vue'

export const NotificationsPage = {
  name: 'NotificationsPage',
  setup() {
    return inject('adminContext')
  },
  template: String.raw`<section v-if="view==='notifications'" class="editor-section"><div class="panel"><div class="admin-toolbar"><div><h2>消息推送</h2><p class="muted">向乘客端或司機端發送站內通知，已記錄 {{notifications.length}} 筆推送。</p></div><div class="notification-toolbar"><select aria-label="消息模板" @change="resetNotification($event.target.value)"><option value="order">訂單確認</option><option value="payment">餘額增值</option><option value="promotion">餘額提現</option><option value="system">訂單退款</option></select><button type="button" v-if="canWrite" @click="resetNotification('order')">新增消息</button></div></div><form v-if="notificationForm" class="record-form notification-form" @submit.prevent="saveNotification"><div class="notification-form-header"><select v-model="notificationForm.audience"><option value="ALL_USERS">全體用戶端</option><option value="ALL_DRIVERS">全體司機端</option><option value="SELECTED">指定用戶／司機</option></select><button type="button" class="secondary" @click="clearNotificationRecipients">清除指定收件人</button></div><div v-if="notificationForm.audience === 'SELECTED'" class="notification-recipient-grid"><input v-model="notificationRecipientSearch" placeholder="搜尋姓名、電話或 ID"/><label>指定用戶端（已選 {{notificationForm.userIds.length}} 位）<select v-model="notificationForm.userIds" multiple size="6"><option v-for="user in filteredNotificationUsers" :key="user.id" :value="user.id">{{user.displayName || user.name || '未命名用戶'}} · {{user.phoneNumber || user.id}}</option></select></label><label>指定司機端（已選 {{notificationForm.driverIds.length}} 位）<select v-model="notificationForm.driverIds" multiple size="6"><option v-for="driver in filteredNotificationDrivers" :key="driver.id" :value="driver.id">{{driver.name || '未命名司機'}} · {{driver.phone || driver.id}}</option></select></label><p class="muted">可使用搜尋縮小清單，按住 Ctrl／Command 可選擇多位收件人。</p></div><input v-model="notificationForm.title" placeholder="消息標題" required/><textarea v-model="notificationForm.content" placeholder="消息內容" rows="5" required/><div class="notification-form-actions"><button type="submit">立即發送</button><button type="button" class="secondary" @click="notificationForm=null">取消</button></div></form><table><thead><tr><th>標題</th><th>內容</th><th>受眾</th><th>建立時間</th></tr></thead><tbody><tr v-for="item in notifications" :key="item.id"><td>{{item.title}}</td><td>{{item.content}}</td><td>{{item.audience === 'USER' || item.audience === 'ALL_USERS' ? '用戶端' : '司機端'}}</td><td>{{formatDate(item.createdAt, true)}}</td></tr><tr v-if="!notifications.length"><td colspan="4" class="muted">尚未發送消息</td></tr></tbody></table></div></section>`
}
