import { inject } from 'vue'

export const RoutePricingPage = {
  name: 'RoutePricingPage',
  setup() {
    return inject('adminVehiclePricingContext')
  },
  template: String.raw`<section v-if="view==='route-pricing'" class="editor-section route-pricing-admin"><div class="panel"><div class="admin-toolbar"><div><h2>路線最低價</h2><p class="muted">在原有距離計價結果上設定出發地到目的地的最低車資（使用目前定價貨幣）。</p></div><button type="button" v-if="canWrite" @click="resetRouteMinimumFare">新增規則</button></div><div v-if="routeMinimumFareForm" class="modal-backdrop" @click.self="routeMinimumFareForm=null"><form class="record-form route-minimum-fare-editor" @submit.prevent="saveRouteMinimumFare"><h3>{{routeMinimumFareForm.id ? '編輯路線最低價' : '新增路線最低價'}}</h3><p class="muted">設定路線、車輛類別與最低收費；未指定車輛類別時套用所有車種。</p><select v-model="routeMinimumFareForm.originRegion" required><option>香港</option><option>澳門</option><option>大陸</option></select><input v-model="routeMinimumFareForm.originCity" placeholder="出發城市（留空代表全部）"/><select v-model="routeMinimumFareForm.destinationRegion" required><option>香港</option><option>澳門</option><option>大陸</option></select><input v-model="routeMinimumFareForm.destinationCity" placeholder="目的城市（留空代表全部）"/><select v-model="routeMinimumFareForm.categoryId"><option value="">所有車種</option><option v-for="category in categories" :key="category.id" :value="category.id">{{category.name}}</option></select><input v-model.number="routeMinimumFareForm.minimumFare" type="number" min="0" step="0.01" placeholder="最低金額" required/><input :value="pricingCurrency === 'HKD' ? 'HKD$（系統定價貨幣）' : 'RMB¥（系統定價貨幣）'" readonly/><label><input v-model="routeMinimumFareForm.enabled" type="checkbox"/> 啟用</label><div class="editor-actions"><button type="button" class="secondary" @click="routeMinimumFareForm=null">取消</button><button type="submit">{{routeMinimumFareForm.id ? '保存修改' : '新增規則'}}</button></div></form></div><table><thead><tr><th>路線</th><th>車種</th><th>最低金額</th><th>狀態</th><th>操作</th></tr></thead><tbody><tr v-for="item in routeMinimumFares" :key="item.id"><td>{{item.originRegion}}{{item.originCity ? ' · '+item.originCity : ''}} → {{item.destinationRegion}}{{item.destinationCity ? ' · '+item.destinationCity : ''}}</td><td>{{categories.find(category => category.id === item.categoryId)?.name || '所有車種'}}</td><td>{{item.currency}}{{item.minimumFare.toFixed(2)}}</td><td>{{item.enabled ? '啟用' : '停用'}}</td><td class="row-actions"><button type="button" v-if="canWrite" @click="editRouteMinimumFare(item)">編輯</button><button type="button" v-if="canWrite" @click="removeRouteMinimumFare(item)">刪除</button></td></tr></tbody></table></div></section>`
}
