export function createRoutePricingActions({ api, pricingCurrency, distancePricing, routeMinimumFareForm, error, load, displayError, requestConfirmation, notify, t }) {
  function addPricingTier(pricing) { const previous = pricing.tiers.at(-1); if (previous) previous.toKm = previous.toKm ?? previous.fromKm + 20; pricing.tiers.push({ id: `${pricing.categoryId}-tier-${Date.now()}`, fromKm: previous?.toKm ?? 0, toKm: null, pricePerKm: 0, order: pricing.tiers.length + 1 }) }
  function removePricingTier(pricing, index) { pricing.tiers.splice(index, 1); pricing.tiers.forEach((tier, tierIndex) => { tier.order = tierIndex + 1; if (tierIndex > 0) tier.fromKm = pricing.tiers[tierIndex - 1].toKm }); if (pricing.tiers.length) pricing.tiers.at(-1).toKm = null }
  function syncPreviousTier(pricing, index) { if (index > 0) pricing.tiers[index - 1].toKm = pricing.tiers[index].fromKm }
  function syncNextTier(pricing, index) { const tier = pricing.tiers[index]; if (index < pricing.tiers.length - 1) pricing.tiers[index + 1].fromKm = tier.toKm }
  async function saveDistancePricing(pricing) { try { await api(`/admin/distance-pricing/${pricing.categoryId}`, { method: 'POST', body: JSON.stringify(pricing) }); await load() } catch (err) { error.value = displayError(err) } }
  async function switchPricingCurrency() { try { await api('/admin/distance-pricing/currency', { method: 'POST', body: JSON.stringify({ currency: pricingCurrency.value }) }); await load() } catch (err) { error.value = displayError(err) } }
  function resetRouteMinimumFare() { routeMinimumFareForm.value = { id: '', originRegion: '香港', originCity: '', destinationRegion: '大陸', destinationCity: '', categoryId: '', minimumFare: 800, currency: pricingCurrency.value === 'HKD' ? 'HKD$' : 'RMB¥', enabled: true } }
  function editRouteMinimumFare(item) { routeMinimumFareForm.value = { ...item, originCity: item.originCity || '', destinationCity: item.destinationCity || '', categoryId: item.categoryId || '' } }
  async function saveRouteMinimumFare() { try { await api('/admin/route-minimum-fares', { method: 'POST', body: JSON.stringify(routeMinimumFareForm.value) }); routeMinimumFareForm.value = null; await load() } catch (err) { error.value = displayError(err) } }
  async function removeRouteMinimumFare(item) { if (!await requestConfirmation({ title: '刪除路線最低價', message: `${t('remove')} ${item.originRegion} → ${item.destinationRegion}?`, confirmLabel: '刪除', danger: true })) return; try { await api(`/admin/route-minimum-fares/${item.id}`, { method: 'DELETE' }); notify('路線最低價已刪除'); await load() } catch (err) { error.value = displayError(err); notify(error.value, 'error') } }
  return { addPricingTier, removePricingTier, syncPreviousTier, syncNextTier, saveDistancePricing, switchPricingCurrency, resetRouteMinimumFare, editRouteMinimumFare, saveRouteMinimumFare, removeRouteMinimumFare }
}
